version: '3.1'

networks:
  portfolio:

services:
  postgres:
    build: postgres
    networks:
      portfolio:
    ports:
      - "5432:5432"
    env_file:
      - .env.local

  portfolio-api:
    build: .
    networks:
      portfolio:
    env_file:
      - .env.local
    depends_on:
      - postgres

  portfolio-frontend:
    build:
      context: frontend
      args:
        REACT_APP_API_BASE_URL: http://192.168.99.100/api
        REACT_APP_BASE_URL: http://192.168.99.100
    ports:
      - "80:80"
    networks:
      portfolio:
    depends_on:
      - portfolio-api
