version: '3.1'

networks:
  portfolio:

services:
  postgres:
    build: postgres
    ports:
      - "5432:5432"
    volumes:
      - "~/database_data:/var/lib/postgresql/data"
    networks:
      portfolio:
    env_file:
      - .env.prod

  portfolio-api:
    build: .
    networks:
      portfolio:
    env_file:
      - .env.prod
    depends_on:
      - postgres

  portfolio-frontend:
    build:
      context: frontend
      args:
        REACT_APP_API_BASE_URL: http://prashantchaubey.com/api
        REACT_APP_BASE_URL: http://prashantchaubey.com
    networks:
      portfolio:
    ports:
     - "80:80"
    depends_on:
      - portfolio-api