version: '3.1'

networks:
  portfolio:

services:
  postgres:
    build: postgres
    networks:
      portfolio:
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password

  portfolio-api:
    build: .
    networks:
      portfolio:
    environment:
      DB_HOST: postgres
      DB_NAME: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
    depends_on:
      - postgres

  portfolio-frontend:
    build:
      context: frontend
      args:
        # This configuration is needed during building time so passing as an "arg"
        REACT_APP_API_URL: "http://192.168.99.100/api/v1"
    ports:
      - "80:80"
    networks:
      portfolio:
    depends_on:
      - portfolio-api
