version: '3.1'

networks:
  my_net:

services:
  website:
    build: .
    ports:
      - "8080:8080"
    networks:
      my_net:
        aliases:
          - "website"

  elasticsearch:
    image: elasticsearch:7.5.1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      my_net:
        aliases:
          - "elasticsearch"
    environment:
      discovery.type: single-node
