version: '3.1'

networks:
  my_net:

services:
  postgres:
    build: postgres
    ports:
      - "5432:5432"
    networks:
      my_net:
        aliases:
          - "postgres"
    environment:
      POSTGRES_PASSWORD: "password"

  website:
    depends_on:
      - postgres
    build: .
    ports:
      - "8080:8080"
    networks:
      my_net:
        aliases:
          - "website"

  elasticsearch:
    build: elastic-search
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      my_net:
        aliases:
          - "elasticsearch"
    environment:
      discovery.type: single-node
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"

  logstash:
    build: logstash
    depends_on:
      - elasticsearch
      - kibana
      - postgres
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
      DB_HOST: "postgres"
      DB_NAME: "postgres"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "password"
    networks:
      my_net:
        aliases:
          - "logstash"

  kibana:
    build: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      my_net:
        aliases:
          - "kibana"